version: '3.5'

services:

  sms:
    image: yuttasakcom/nexmo-sms:1.0.1
    container_name: sms
    depends_on:
      - mongo
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  mongo:
    image: mongo:3.6.4
    container_name: mongo
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
    driver: local